SELECT * FROM STUDENT
SELECT * FROM STUDENT WHERE AGE>= 10 AND AGE <=20
SELECT name FROM STUDENT
SELECT * FROM STUDENT WHERE name LIKE '%o%'
SELECT * FROM STUDENT WHERE age < id
SELECT * FROM STUDENT order by age